FROM mambaorg/micromamba:0.15.2

COPY --chown=micromamba:micromamba environment.yaml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes

# Install curl for Codecov
RUN apt-get update && apt-get upgrade -y && apt-get install -y curl
