FROM continuumio/miniconda3:4.9.2-alpine

WORKDIR /opt/app

COPY environment.yml ./

RUN apk update && apk upgrade && \
    apk add --no-cache git bash

RUN conda env create -f environment.yml && \
    conda clean --all --yes

SHELL ["conda", "run", "-n", "planckton", "/bin/ash", "-c"]
ENV PATH /opt/conda/envs/planckton/bin:$PATH
ENV CONDA_DEFAULT_ENV $conda_env
