FROM continuumio/miniconda3:4.9.2-alpine

WORKDIR /opt/app

COPY environment.yml ./

RUN conda env create -f environment.yml && \
    conda clean --all --yes

SHELL ["conda", "run", "-n", "planckton", "/bin/ash", "-c"]

RUN pip install .
